# This file was generated by GoReleaser. DO NOT EDIT.
cask "trimdown" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "1b3a1c678cf0b02ea0b9baaa3e6947756308f557dde450c8955a935736ed683f"
      url "https://github.com/itssoumit/trimdown/releases/download/v#{version}/trimdown_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9648ffb6aac9900016124b3122512b38edf9621ae4c66832c57a68b75c1e3819"
      url "https://github.com/itssoumit/trimdown/releases/download/v#{version}/trimdown_darwin_arm64.tar.gz"
    end
  end

  name "trimdown"
  desc "CLI proxy that compresses tool output to cut LLM token use."
  homepage "https://github.com/itssoumit/trimdown"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "trimdown"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/trimdown"]
    end
  end

  # No zap stanza required

end
