# This file was generated by GoReleaser. DO NOT EDIT.
cask "trimdown" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "8e0f85287c82e80938e2f9e4fe57fd2658b751df743bdb629f0381b12caa53b0"
      url "https://github.com/itssoumit/trimdown/releases/download/v#{version}/trimdown_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2085ad5b20dce5fa6d36102174e1952874f169e695993c678585fb5567ab9e68"
      url "https://github.com/itssoumit/trimdown/releases/download/v#{version}/trimdown_darwin_arm64.tar.gz"
    end
  end

  name "trimdown"
  desc "CLI proxy that compresses tool output to cut LLM token use."
  homepage "https://github.com/itssoumit/trimdown"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "trimdown"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/trimdown"]
    end
  end

  # No zap stanza required

end
