# This file was generated by GoReleaser. DO NOT EDIT.
cask "trimdown" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "f6982ae0bb0622b2f9180ec5af93c926c89e86e5440517c40f24e8c42b4ca24b"
      url "https://github.com/itssoumit/trimdown/releases/download/v#{version}/trimdown_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "83e4a0c161e465ca200c89091286816b9b4b55fe52675e4dde4fe5b8658bd562"
      url "https://github.com/itssoumit/trimdown/releases/download/v#{version}/trimdown_darwin_arm64.tar.gz"
    end
  end

  name "trimdown"
  desc "CLI proxy that compresses tool output to cut LLM token use."
  homepage "https://github.com/itssoumit/trimdown"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "trimdown"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/trimdown"]
    end
  end

  # No zap stanza required

end
